### ISSUE TITLE
Long text

### ISSUE THREAD

**Issue by joeymok** [fulldecent/FDTextFieldTableViewCell#4] opened 2016-10-04 09:18 UTC
When I type a very long text in the TextField, it cover the label on the left.

**Comment by fulldecent** [comment] 2016-10-04 20:43
I see. 

This should go underneath, or truncate.

Let's compare to what other apps from Apple do.

**Comment by fulldecent** [comment] 2017-01-04 04:07
What should the expected behavior be? And have you seen another that works the way we should make this work?

**Comment by joeymok** [comment] 2017-01-04 04:53
Go underneath looks better. Like typing the WiFi password in iPhone Settings.

**Comment by fulldecent** [comment] 2019-10-28 21:50
Thank you. Can a screenshot of this please be added here

**Comment by fulldecent** [comment] 2019-12-01 19:18
Please add a screenshot showing the new behavior

**Comment by yaroslav-zhurakovskiy** [comment] 2019-12-01 19:26
It looks like it works normally. The text goes underneath the label.
<img width="547" alt="Screenshot 2019-11-28 at 22 23 04" src="https://user-images.githubusercontent.com/3489125/69919012-332ac880-1481-11ea-9b2a-b2340751a576.png">

**Comment by fulldecent** [comment] 2019-12-01 21:22
Looks great, thank you. This looks fixed now.

**Closed as completed by fulldecent** 2019-12-01 21:22 UTC
